spring:
  application:
    name: TodoApplication
server:
  port: 8080
elastic:
  index: todo-index
  tsPipeline: timestamp-pipeline
es:
  hostname: my-deployment-alias-restaurants-001.es.us-west-1.aws.found.io
  scheme: https
  port: 443
  apikeyid: ${API_KEY_ID}
  apikeysecret: ${API_KEY_SECRET}
